version: '3'

services:
  mysql:
    image: mysql:5.6
    restart: always
    volumes:
      - ./database.sql:/docker-entrypoint-initdb.d/database.sql
    environment:
      - MYSQL_DATABASE=kcsc
      - MYSQL_ROOT_PASSWORD=root
  web:
    build: .
    depends_on:
      - mysql
    ports:
      - '10666:80'
    volumes:
      - ./src:/var/www/html
    stdin_open: true
