version: '3.5'
services:
  mysql:
    image: mysql:5.6
    restart: always
    volumes:
      - ./db/schema.sql:/docker-entrypoint-initdb.d/database.sql
    environment:
      - MYSQL_DATABASE=kmactf
      - MYSQL_ROOT_PASSWORD=mauFJcuf5dhRMQrjj
  web:
    build: .
    depends_on:
      - mysql
    ports:
      - '20108:80'
    volumes:
      - ./src:/var/www/html
    stdin_open: true
volumes:
  db:
    driver: local